export interface IUser {
     id:number,
     title: string,
     firstName: string,
     middleName: string,
     lastName: string,
     emailId: string,
     dob: string,
     gender: string,
     password: string,
     confirmPassword: string,
     companyId: string,
     projectId: string,
     corporatePostion: string,
     empCode: number,
     roleId: string,
     address: string,
     countryId: string,
     stateId: string,
     city: string,
     officeId: string,
     reportTo: string,
     agentPhoneNumber: number,
     phoneNo: number
 }
